steps:
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['--version']
     
steps:
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['test']

steps:
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']

  
  
